"""XLSX export formatting/redaction and export -> import round-trip integrity."""
import io
from datetime import datetime

import pytest
from mongomock_motor import AsyncMongoMockClient
from openpyxl import load_workbook

import exports
import imports as data_imports

from .docs_support import DOMAIN, NOW, env, hdr, seed, server, snapshot  # noqa: F401  (env is a fixture)

pytestmark = pytest.mark.anyio

ROUND_TRIP_FIELDS = ("name", "category", "qr_code", "sku", "model", "serial_number", "condition", "location",
                     "quantity", "available", "daily_rate", "tracking_type", "notes", "equipment_family")


async def export_bytes(env, dataset, role="admin", fmt="xlsx", **filters):
    ds = exports.resolve_dataset(dataset)
    docs = await env.db[ds.source].find(ds.query(exports.clean_filters(ds, filters)), {"_id": 0}).sort(*ds.sort).to_list(None)
    docs = [server.redact_money_for_crew(d, role) for d in docs]
    return exports.render_xlsx(ds, docs, role, brand="Concrete Form", generated_by="Tester", filters=filters), docs


def sheet_rows(content: bytes, name="Data"):
    ws = load_workbook(io.BytesIO(content))[name]
    return [[c.value for c in row] for row in ws.iter_rows()]


async def test_xlsx_is_formatted_and_typed(env):
    content, docs = await export_bytes(env, "equipment")
    wb = load_workbook(io.BytesIO(content))
    assert wb.sheetnames == ["Data", "Report Info"]
    ws = wb["Data"]
    assert ws.freeze_panes == "A2" and ws.auto_filter.ref.startswith("A1:")
    assert ws["A1"].font.bold and ws["A1"].fill.fgColor.rgb.endswith("1F2937")
    header = [c.value for c in ws[1]]
    rate_col = header.index("Daily Rate") + 1
    qty_col = header.index("Owned") + 1
    assert ws.cell(2, rate_col).number_format == "#,##0.00"
    assert isinstance(ws.cell(2, qty_col).value, int), "numbers must stay numeric, not text"
    info = dict(sheet_rows(content, "Report Info"))
    assert info["Records"] == len(docs) and info["Dataset"] == "equipment" and info["Generated by"] == "Tester"


async def test_crew_xlsx_has_no_money_columns_or_values(env):
    content, _ = await export_bytes(env, "equipment", role="crew")
    rows = sheet_rows(content)
    assert "Daily Rate" not in rows[0]
    assert not any(isinstance(v, float) and v in (12.5, 8.0, 1.5) for r in rows[1:] for v in r)
    consumables, _ = await export_bytes(env, "consumables", role="crew")
    assert "Cost" not in sheet_rows(consumables)[0] and "Price" not in sheet_rows(consumables)[0]


@pytest.mark.parametrize("dataset,filters,column,expected", [
    ("tools", {}, "Name", {"Hammer Drill", "Circular Saw", "Broken Grinder", "Dominick Level"}),
    ("damaged", {}, "Name", {"Strongback 8ft", "Broken Grinder"}),
    ("assignments", {}, "Tool", {"Hammer Drill", "Dominick Level"}),
    ("assignments", {"checked_out_to": "nick"}, "Tool", {"Hammer Drill"}),  # word-start, case-insensitive: not "Dominick"
    ("equipment", {"category": "strongback"}, "Name", {"Strongback 8ft"}),
    ("consumables", {}, "Product", {"Foam Adhesive"}),
    ("block", {}, "Product", {"ICF Block 8in"}),
    ("shop_tasks", {"assignee": "nick"}, "Task", {"Sharpen blades"}),
    ("returns", {}, "ID", {"d2-cccccccc"[:8]}),
    ("outbound", {}, "ID", {"d1-bbbbbbbb"[:8]}),
])
async def test_new_datasets_select_the_right_records(env, dataset, filters, column, expected):
    content, _ = await export_bytes(env, dataset, **filters)
    rows = sheet_rows(content)
    idx = rows[0].index(column)
    assert {r[idx] for r in rows[1:]} == expected, rows


async def test_filter_values_are_never_treated_as_regex_or_operators(env):
    content, _ = await export_bytes(env, "assignments", checked_out_to=".*")
    assert sheet_rows(content)[1:] == []
    with pytest.raises(exports.ExportError):
        exports.clean_filters(exports.resolve_dataset("assignments"), {"$where": "1"})


async def test_aliases_resolve_to_datasets():
    assert exports.resolve_dataset("Inventory").name == "equipment"
    assert exports.resolve_dataset("tool-assignments").name == "assignments"
    assert exports.resolve_dataset("damaged items").name == "damaged"


async def test_formula_text_is_stored_inert_and_round_trips(env):
    evil = "=HYPERLINK(\"http://evil\",\"x\")"
    await env.db.equipment.update_one({"qr_code": "Q-101"}, {"$set": {"notes": evil}})
    content, _ = await export_bytes(env, "equipment")
    ws = load_workbook(io.BytesIO(content))["Data"]
    notes_col = [c.value for c in ws[1]].index("Notes") + 1
    cells = [ws.cell(r, notes_col) for r in range(2, ws.max_row + 1)]
    hit = next(c for c in cells if c.value == evil)
    assert hit.data_type == "s", "text beginning with '=' must not become a formula"
    # and the importer reads it back as the same literal text, not a formula error
    fresh = AsyncMongoMockClient()["fresh"]
    preview = await data_imports.stage_import(fresh, dataset="equipment", filename="e.xlsx", content=content, actor_id="boss", actor_name="Boss")
    assert preview["summary"]["error"] == 0
    row = next(r for r in (await fresh.import_jobs.find_one({"id": preview["import_id"]}))["rows"] if r["data"]["name"] == "Circular Saw")
    assert row["data"]["notes"] == evil


async def test_export_then_import_into_empty_database_reproduces_every_record(env):
    content, docs = await export_bytes(env, "equipment")
    target = AsyncMongoMockClient()["target"]
    preview = await data_imports.stage_import(target, dataset="equipment", filename="inv.xlsx", content=content, actor_id="boss", actor_name="Boss")
    assert preview["summary"] == {"total": len(docs), "create": len(docs), "update": 0, "unchanged": 0, "skip_duplicate": 0, "error": 0}
    assert not preview["blocking_errors"]
    result = await data_imports.commit_import(target, server, import_id=preview["import_id"], plan_hash=preview["plan_hash"], actor_id="boss", actor_name="Boss")
    assert result["result"]["created"] == len(docs)
    imported = {d["sku"]: d for d in await target.equipment.find({}, {"_id": 0}).to_list(None)}
    for original in docs:
        copy = imported[original["sku"]]
        for field in ROUND_TRIP_FIELDS:
            assert (copy.get(field) or None) == (original.get(field) or None), f"{original['name']}.{field}"
    # initial stock goes through the ledger exactly like POST /equipment does
    entries = await target.ledger_entries.find({}, {"_id": 0}).to_list(None)
    assert sum(e["qty"] for e in entries) == sum(d["available"] for d in docs)
    assert all(e["reason"] == "received" for e in entries)


async def test_reimporting_an_unchanged_export_changes_nothing(env):
    content, docs = await export_bytes(env, "equipment")
    before = await snapshot(env.db, *DOMAIN)
    preview = await data_imports.stage_import(env.db, dataset="equipment", filename="inv.xlsx", content=content, actor_id="boss", actor_name="Boss")
    assert preview["summary"]["skip_duplicate"] == len(docs) and preview["summary"]["create"] == 0 and preview["summary"]["error"] == 0
    job = await env.db.import_jobs.find_one({"id": preview["import_id"]})
    assert all(not r["diff"] for r in job["rows"]), "an unchanged export must show zero differences"
    assert await snapshot(env.db, *DOMAIN) == before
    update_preview = await data_imports.stage_import(env.db, dataset="equipment", filename="inv.xlsx", content=content, actor_id="boss", actor_name="Boss", on_duplicate="update")
    assert update_preview["summary"]["unchanged"] == len(docs) and update_preview["summary"]["update"] == 0


async def test_consumables_round_trip(env):
    content, docs = await export_bytes(env, "consumables")
    target = AsyncMongoMockClient()["t2"]
    preview = await data_imports.stage_import(target, dataset="consumables", filename="c.xlsx", content=content, actor_id="boss", actor_name="Boss")
    await data_imports.commit_import(target, server, import_id=preview["import_id"], plan_hash=preview["plan_hash"], actor_id="boss", actor_name="Boss")
    item = await target.sellable_items.find_one({"product": "Foam Adhesive"}, {"_id": 0})
    assert item["kind"] == "consumable" and item["quantity_on_hand"] == 12 and item["cost"] == 5.0 and item["price"] == 9.0
